### ISSUE TITLE
IAP using deprecated RequestProductPurchaseAsync method

### ISSUE THREAD

**Issue by stammen** [microsoftarchive/plugin-x#1]
Is this just a warning for the IAP simulator?

1>d:\github\plugin-x\plugins\microsoftiap\proj.win8.1-universal\microsoftiap\microsoftiap.shared\plugin.cpp(216): warning C4973: 'Windows::ApplicationModel::Store::CurrentAppSimulator::RequestProductPurchaseAsync' : marked as deprecated
1>          Message: 'RequestProductPurchaseAsync(productId, includeReceipt) may be altered or unavailable for releases after Windows 8.1. Instead, use RequestProductPurchaseAsync(productId).'
1>d:\github\plugin-x\plugins\microsoftiap\proj.win8.1-universal\microsoftiap\microsoftiap.shared\plugin.cpp(219): warning C4973: 'Windows::ApplicationModel::Store::CurrentApp::RequestProductPurchaseAsync' : marked as deprecated
1>          Message: 'RequestProductPurchaseAsync(productId, includeReceipt) may be altered or unavailable for releases after Windows 8.1. Instead, use RequestProductPurchaseAsync(productId).'

**Comment by adiviness** [comment]
I don't believe it is a warning only for the simulator, as of commits dfaa105 and 9be0b68 the v3_winrt and v4_winrt branches use the non-deprecated version of the function.
